export const SUN_HIGHLIGHT_ALPHA = 0.35;
export const SUN_HIGHLIGHT_OFFSET_RATIO = 0.3;
export const SUN_HIGHLIGHT_RADIUS_RATIO = 0.35;

const HALF = 0.5;
const PERCENT = 100;

export const SUN_HIGHLIGHT_CENTER_PERCENT =
  (HALF - SUN_HIGHLIGHT_OFFSET_RATIO * HALF) * PERCENT;
export const SUN_HIGHLIGHT_SIZE_PERCENT = SUN_HIGHLIGHT_RADIUS_RATIO * PERCENT;
